Description of meanshift_post
meanshift_post
PURPOSE
Some post processing routines for meanshift not currently being used.
SYNOPSIS
function [IDX,C] = meanshift_post(X, IDX, C, minCsize, forceoutliers)
DESCRIPTION
 Some post processing routines for meanshift not currently being used.
 DATESTAMP
   29-Sep-2005  2:00pm
CROSS-REFERENCE INFORMATION
This function calls:
dist_euclidean Calculates the Euclidean distance between vectors [FAST].
ticstatus Used to display the progress of a long process.
tocstatus Used to display the progress of a long process.
This function is called by: