Description of behaviorAnnotator
behaviorAnnotator
PURPOSE
Caltech Behavior Annotator.
SYNOPSIS
function behaviorAnnotator(fName, aName, tName)
DESCRIPTION
 Caltech Behavior Annotator.
 Can only be used to annotated seq files. To annotate other types of video
 files, they need to be converted to seq files first. For example, to
 convert an avi file into an seq file, use the following command:
  seqIo([seqName],'frImgs',struct('codec','jpg'),'aviName',[aviName])
 Where [seqName] denotes the name of the seq you want to save to and
 [aviName] is the avi file. See seqIo and seqIo>frimgs for more details.
 Use arrow keys to play the video. Controls are as follows:
 (1) If stopped: [L] play backward, [R] play forward
 (2) If playing forward: [L] halve speed, [R] double speed, [U/D] stop
 (3) If playing backward: [L] double speed, [R] halve speed,[U/D] stop
 You can explicitly enter a frame or use the slider to jump in the video.
 USAGE
  behaviorAnnotator( [fName], [aName], [tName] )
 INPUTS
  fName    - optional seq file to load at start
  aName    - optional annotation file to load or import at start
  tName    - optional tracking or detection file to load at start
 OUTPUTS
 EXAMPLE
  behaviorAnnotator
 See also behaviorData, seqIo
 Piotr's Image&Video Toolbox      Version 2.60
 Copyright 2010 Piotr Dollar.  [pdollar-at-caltech.edu]
 Please email me if you find bugs, or have suggestions or questions!
 Licensed under the Lesser GPL [see external/lgpl.txt]
CROSS-REFERENCE INFORMATION
This function calls:
behaviorData Retrieve and manipulate behavior annotation of a video.
seqIo Utilities for reading and writing seq files.
c clc - clear command window.
int2str2 Convert integer to string of given length; improved version of int2str.
plotEllipse Adds an ellipse to the current plot.
uniqueColors Generate m*n visually distinct RGB colors suitable for display.
This function is called by: