Description of histc_sift_nD
histc_sift_nD
PURPOSE
Creates a series of locally position dependent histograms.
SYNOPSIS
function hs = histc_sift_nD(I, edges, pargmask, weightmask, multch)
DESCRIPTION
 Creates a series of locally position dependent histograms.
 Creates a series of locally position dependent histograms of the values in the mutiple
 channel multidimensional array I (this is a generalized version of histc_sift that
 allows for multiple channels).
 I is an M1xM2x...xMkxnd array, it consists of nd channels each of dimension
 (M1xM2x...xMk).  histc_sift_nD works by dividing a (M1xM2x...xMk) array into seperate
 regions and creating a 1D histogram for each using histc_1D.  histc_sift_nD does the same
 thing except each region now has multiple channels, and an nd-dimensional histogram is
 created for each using histc_nD.
 INPUTS
   I           - M1xM2x...xMkxnd array, (nd channels each of dim M1xM2x...xMk)
   edges       - parameter to histc_nD, [either scalar, vector, or cell vector]
   pargmask    - cell of parameters to mask_gaussians
   weightmask  - [optional] M1xM2x...xMk numeric array of weights
   multch      - [optional] if 0 this becomes same as histc_sift.m (nd==1)
 OUTPUTS
   hs          - histograms (array of size nmasks x nbins)
 EXAMPLE
   G = filter_gauss_nD([100 100],[],[],0);
   hs = histc_sift_nD( cat(3,G,G), 5, {2,.6,.1,0} );
   hs = histc_sift_nD( cat(3,G,randn(size(G))),5,{2,.6,.1,0});
   figure(1); montage2(hs,1);  figure(2); montage2(hs,1);
 DATESTAMP
   29-Sep-2005  2:00pm
 See also HISTC_1D, HISTC_SIFT, MASK_GAUSSIANS, HISTC_ND
CROSS-REFERENCE INFORMATION
This function calls:
gauss_smooth Applies Gaussian smoothing to a (multidimensional) image.
histc_1D Generalized, version of histc (histogram count), allows weighted values.
histc_nD Generalized, multidimensional version of normalized histc (histogram count).
mask_gaussians Divides a volume into softly overlapping gaussian windows.
This function is called by:
histc_sift Creates a series of locally position dependent histograms of the values in I.