Description of im
im
PURPOSE
Function for displaying grayscale images.
SYNOPSIS
function varargout = im(I, range, extraInf)
DESCRIPTION
 Function for displaying grayscale images.
 Handy function for showing a grayscale or color image with a colorbar.
 USAGE
  h = im( I, [range], [extraInf] )
 INPUTS
  I        - image in a valid format for imagesc
  range    - [] minval/maxval for imagesc
  extraInf - [1] if 1 then colorbar is shown as well as tick marks
 OUTPUTS
  h        - handle for image graphics object
 EXAMPLE
  load clown; im( X )
 See also imshow, imview, impixelinfo, imtool, imagesc
 Piotr's Image&Video Toolbox      Version 2.41
 Copyright 2009 Piotr Dollar.  [pdollar-at-caltech.edu]
 Please email me if you find bugs, or have suggestions or questions!
 Licensed under the Lesser GPL [see external/lgpl.txt]
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
demoCluster Clustering demo.
distMatrixShow Useful visualization of a distance matrix of clustered points.
meanShiftImExplore Visualization to help choose sigmas for meanShiftIm.
pcaVisualize Visualization of quality of approximation of X given principal comp.
FbApply2d Applies each of the filters in the filterbank FB to the image I.
FbReconstruct2d Use to see how much image information is preserved in filter outputs.
FbVisualize Used to visualize a series of 1D/2D/3D filters.
filterVisualize Used to visualize a 1D/2D/3D filter.
bbGt Bounding box (bb) annotations struct, evaluation and sampling routines.
imMlGauss Calculates max likelihood params of Gaussian that gave rise to image G.
imagesAlign Fast and robust estimation of homography relating two images.
imtransform2 Applies a linear or nonlinear transformation to an image I.
maskGaussians Divides a volume into softly overlapping gaussian windows.
maskSphere Creates an 'image' of a n-dimensional hypersphere.
optFlowCorr Calculate optical flow using cross-correlation.
optFlowHorn Calculate optical flow using Horn & Schunck.
optFlowLk Calculate optical flow using Lucas & Kanade. Fast, parallel code.