Description of imtransform2
imtransform2
PURPOSE
Applies a general/special homography on an image I
SYNOPSIS
function J = imtransform2(I, varargin)
DESCRIPTION
 Applies a general/special homography on an image I
 Takes the center of the image as the origin, not the top left corner.
 Also, the coordinate system is row/column format, so H must be also.
 The bounding box of the image is set by the BBOX argument, a string that
 can be 'loose' (default) or 'crop'. When BBOX is 'loose', J includes the
 whole transformed image, which generally is larger than I. When BBOX is
 'crop' J is cropped to include only the central portion of the
 transformed image and is the same size as I. The 'loose' flag is
 currently inexact (because of some padding/cropping). Preserves I's type.
 USAGE
  J=imtransform2(I,H,[method],[bbox],[show],[pad])     % general hom
  J=imtransform2(I,angle,[method],[bbox],[show],[pad]) % rotation
  J=imtransform2(I,dx,dy,[method],[bbox],[show],[pad]) % translation
 INPUTS - common
  I       - 2D image [converted to double]
  method  - ['linear'] 'nearest', 'spline', 'cubic' (for interp2)
  bbox    - ['loose'] or 'crop'
  show    - [0] figure to use for optional display
  pad     - [0] padding value (scalar or 'replicate')
 INPUTS - specific to general homography
  H       - 3x3 nonsingular homography matrix
 INPUTS - specific to rotation
  angle   - angle to rotate in degrees
 INPUTS - specific to translation
  dx      - x translation (right)
  dy      - y translation (up)
 OUTPUTS
  J       - transformed image
 EXAMPLE - general homography (rotation + translation)
  load trees; I=X; method='linear';
  R = rotationMatrix(pi/4); T=[1; 3]; H=[R T; 0 0 1];
  J = imtransform2(I,H,method,'crop',1,'replicate');
 EXAMPLE - general homography (out of plane rotation)
  load trees; I=X; method='nearest';
  R = rotationMatrix([0 1 0],pi/4); z=500;
  H = R; H(1:2,:)=H(1:2,:)*z; H(:,3)=H(:,3)*z;
  J = imtransform2(I,H,method,'loose',1);
 EXAMPLE - rotation
  load trees; I=X; method='bicubic';
  tic; J1 = imrotate(I,55,method,'crop'); toc
  tic; J2 = imtransform2(I,55,method,'crop'); toc
  clf; subplot(2,2,1); im(I); subplot(2,2,2); im(J1-J2);
  subplot(2,2,3); im(J1); subplot(2,2,4); im(J2);
 EXAMPLE - translation
  load trees; I=X; method='bicubic';
  J = imtransform2(X,0,1.5,method,'crop');
  figure(1); clf; im(I,[0 128]); figure(2); clf; im(J,[0 128]);
 See also TEXTUREMAP, INTERP2
 Piotr's Image&Video Toolbox      Version 2.53
 Copyright 2010 Piotr Dollar.  [pdollar-at-caltech.edu]
 Please email me if you find bugs, or have suggestions or questions!
 Licensed under the Lesser GPL [see external/lgpl.txt]
CROSS-REFERENCE INFORMATION
This function calls:
im Function for displaying grayscale images.
rotationMatrix Performs different operations dealing with a rotation matrix
This function is called by:
jitterImage Creates multiple, slightly jittered versions of an image.