Description of makemovies
makemovies
PURPOSE
[4D] Used to convert R sets of equal length videos into a single movie.
SYNOPSIS
function M = makemovies(IS, montage2params)
DESCRIPTION
 [4D] Used to convert R sets of equal length videos into a single movie.
 To display same data statically use montages.
 Works by calling montage2 once per frame.
 INPUTS
   IS              - MxNxTxR or MxNx1xTxR or MxNx3xTxR array, or cell array where each
                     element is an MxNxT or MxNx1xT or MxNx3xT array
   montage2params  - [optional] params for montage2 -- ex: {showlines, extrainfo}
 OUTPUTS
   M               - resulting movie
 EXAMPLE
   load( 'images.mat' );
   M = makemovies( videos );
   movie( M );
 DATESTAMP
   29-Sep-2005  2:00pm
 See also MONTAGES, MONTAGE2, MAKEMOVIE, MAKEMOVIESETS, PLAYMOVIES
CROSS-REFERENCE INFORMATION
This function calls:
montage2 [3D] Used to display a stack of T images.
cell2array Converts a cell array into a regular array.
figureresized Creates a figures that takes up certain area of screen.
This function is called by:
pca_visualize Visualization of quality of approximation of X given principal components.