Description of makemoviesets
makemoviesets
PURPOSE
[5D] Used to convert S sets of R videos into a movie.
SYNOPSIS
function M = makemoviesets(IS, montagesparams)
DESCRIPTION
 [5D] Used to convert S sets of R videos into a movie.
 Each group of videos is shown in a subplot.
 Works by calling montages once per frame.
 INPUTS
   IS              - MxNxTxRxS or MxNx1xTxRxS or MxNx3xTxRxS array, or cell array where
                     each element is an MxNxTxR or MxNx1xTxR or MxNx3xTxR array
   montagesparams  - [optional] cell array of params for montages
 OUTPUTS
   M               - resulting movie
 EXAMPLE
   load( 'images.mat' );
   videoclusters = clustermontage( videos, IDXv, 9, 1 );
   M = makemoviesets( videoclusters );
   movie( M );
 DATESTAMP
   29-Sep-2005  2:00pm
 See also MAKEMOVIE, MAKEMOVIESETS2, CLUSTERMONTAGE
CROSS-REFERENCE INFORMATION
This function calls:
montages [4D] Used to display R sets of T images each.
c clc
figureresized Creates a figures that takes up certain area of screen.
This function is called by: