Description of mask_sphere
mask_sphere
PURPOSE
Creates an 'image' of a n-dimensional hypersphere.
SYNOPSIS
function mask = mask_sphere(d, r, show)
DESCRIPTION
 Creates an 'image' of a n-dimensional hypersphere.
 Useful for testing visualization procedures.
 Create a d-dimensional matrix mask of dimensions [s x s x s x ... x s]
 where s=2r+1.  Each element mask(x1,x2...,xd) is 1 if (x1,...xd) falls
 inside the centered hypersphere of rad r.
 In 1d this corresponds to a vector of the form [.. 0 1 1 1 1 1 0 ..]
 In 2d this corresponds to an image of a white circle.
 In 3d and 4d, well try it and 'see' what it looks like.
 USAGE
  mask = mask_sphere( d, r, [show] )
 INPUTS
  d         - dimension (any positive integer)
  r         - sphere integer radius
  show      - [] figure in which to display results
 OUTPUTS
  mask      - [s x s x s x ... x s] hypersphere image
 EXAMPLE
  mcircle = mask_sphere( 2, 20, 1 );
  msphere = mask_sphere( 3, 10, 2 );
  msphere = mask_sphere( 4, 10, 3 );
 See also MASK_CIRCLE, MONTAGE2, MONTAGES2
CROSS-REFERENCE INFORMATION
This function calls:
im IM [2D] Function for displaying grayscale images.
montage2 [3D] Used to display a stack of T images.
montages2 MONTAGES2 [4D] Used to display R sets of T images each.
This function is called by: