Description of montages2
montages2
PURPOSE
MONTAGES2 [4D] Used to display R sets of T images each.
SYNOPSIS
function varargout = montages2(IS, montage2params, padsize)
DESCRIPTION
MONTAGES2 [4D] Used to display R sets of T images each.
 Displays one montage (see montage2) per row.  Each of the R image sets is flattened to
 a single long image by concatenating the T images in the set.
 Alternative to montages.
 INPUTS
   IS                  - MxNxTxR or MxNx1xTxR or MxNx3xTxR array
   montage2params      - [optional] params for montage2; ex: {showlines, extrainfo}
   padsize             - [optional] total amount of vertical or horizontal padding
 OUTPUTS
   I                   - 3D or 4D array of flattened images, displayed with montage2
   mm                  - #montages/row
   nn                  - #montages/col
 EXAMPLE
   load( 'images.mat' );
   imageclusters = clustermontage( images, IDXi, 16, 1 );
   montages2( imageclusters );
 DATESTAMP
   29-Sep-2005  2:00pm
 See also MONTAGES, MAKEMOVIES, MONTAGE2, CLUSTERMONTAGE
CROSS-REFERENCE INFORMATION
This function calls:
montage2 [3D] Used to display a stack of T images.
arraycrop2dims Pads or crops I appropriately so that size(IC)==dims.
checknumericargs Helper utility for checking numeric vector arguments.
This function is called by:
makemoviesets2 [5D] Used to convert S sets of R videos into a movie.
mask_gaussians Divides a volume into softly overlapping gaussian windows.