Description of montages
montages
PURPOSE
[4D] Used to display R sets of T images each.
SYNOPSIS
function varargout = montages(IS, montage2prms, labels, montage2lbls)
DESCRIPTION
 [4D] Used to display R sets of T images each.
 Displays one montage (see montage2) per subplot.
 USAGE
  varargout = montages( IS, [montage2prms], [labels], [montage2lbls] )
 INPUTS
   IS            - MxNxTxR or MxNx1xTxR or MxNx3xTxR array, or cell array
                   where each element is MxNxT or MxNx1xT or MxNx3xT
   montage2prms  - [] params for montage2 EXCEPT labels; ex: {showLns}
   labels        - [] cell array of titles for subplots
   montage2lbls  - [] cell of cells of strngs: montage2 lbls for subplots
 OUTPUTS
   mm            - #montages/row
   nn            - #montages/col
 EXAMPLE
  load( 'images.mat' );
  imClusters = clustermontage( images, IDXi, 16, 1 );
  montages( imClusters );
 See also MONTAGES2, MAKEMOVIES, MONTAGE2, CLUSTERMONTAGE
CROSS-REFERENCE INFORMATION
This function calls:
montage2 [3D] Used to display a stack of T images.
This function is called by:
rbfComputeBasis Get locations and sizes of radial basis functions for use in rbf network.
makemoviesets [5D] Used to convert S sets of R videos into a movie.