Description of seqReaderPlugin
seqReaderPlugin
PURPOSE
Plugin for seqIo and videoIO to allow reading of seq files.
SYNOPSIS
function varargout = seqReaderPlugin(cmd, h, varargin)
DESCRIPTION
 Plugin for seqIo and videoIO to allow reading of seq files.
 Do not call directly, use as plugin for seqIo or videoIO instead.
 The following is a list of commands available (srp=seqReaderPlugin):
  h = srp('open',h,fName)    % Open a seq file for reading (h ignored).
  h = srp('close',h);        % Close seq file (output h is -1).
  [I,ts] =srp('getframe',h)  % Get current frame (returns [] if invalid).
  [I,ts] =srp('getframeb',h) % Get current frame with no decoding.
  ts = srp('getts',h)        % Return timestamps for all frames.
  info = srp('getinfo',h)    % Return struct with info about video.
  [I,ts] =srp('getnext',h)   % Shortcut for 'next' followed by 'getframe'.
  out = srp('next',h)        % Go to next frame (out=0 on fail).
  out = srp('seek',h,frame)  % Go to specified frame (out=0 on fail).
  out = srp('step',h,delta)  % Go to current frame+delta (out=0 on fail).
 USAGE
  varargout = seqReaderPlugin( cmd, h, varargin )
 INPUTS
  cmd        - string indicating operation to perform
  h          - unique identifier for open seq file
  varargin   - additional options (vary according to cmd)
 OUTPUTS
  varargout  - output (varies according to cmd)
 EXAMPLE
 See also SEQIO, SEQWRITERPLUGIN
 Piotr's Image&Video Toolbox      Version 2.63
 Copyright 2012 Piotr Dollar.  [pdollar-at-caltech.edu]
 Please email me if you find bugs, or have suggestions or questions!
 Licensed under the Lesser GPL [see external/lgpl.txt]
CROSS-REFERENCE INFORMATION
This function calls:
c clc - clear command window.
int2str2 Convert integer to string of given length; improved version of int2str.
ticStatus Used to display the progress of a long process.
tocStatus Used to display the progress of a long process.
This function is called by:
seqIo Utilities for reading and writing seq files.