Description of nlfilt_sep
nlfilt_sep
PURPOSE
Efficient multidimensional nonlinear but seperable filtering operation.
SYNOPSIS
function I = nlfilt_sep(I, dims, shape, fun, varargin)
DESCRIPTION
 Efficient multidimensional nonlinear but seperable filtering operation.
 The concept of a nonlinear seperable filter is not very common, but nevertheless can
 prove very useful since computation time can be reduced greatly.  Consider a funciton
 like max that is applied to a 2 dimensional window.  max could also be applied to each
 row of the window, then to the resulting column, insead of being applied to the entire
 window simultaneously.  This is what is meant here by a seperable nonlinear filter.
 The function fun must be able to take an input of the form
 C=fun(I,radius,param1,...paramk).  The return C must have the same size as I, and each
 element of C must be the result of applying the nlfilt operation to the local column (of
 size 2r+1) of A.
 For example:
   % COMPUTES LOCAL SUMS:
   C = nlfilt_sep( I, dims, shape, @rnlfilt_sum );
   % COMPUTES LOCAL MAXES:
   C = nlfilt_sep( I, dims, shape, @rnlfilt_max );
 INPUTS
   I       - matrix to compute fun over
   dims    - size of volume to compute fun over
   shape   - 'valid', 'full', or 'same', see conv2 help
   fun     - nonlinear filter
   params  - optional parameters for nonlinear filter
 OUTPUTS
   I      - resulting image
 DATESTAMP
   26-Jan-2006  2:00pm
 See also NLFILTBLOCK_SEP, RNLFILT_SUM, RNLFILT_MAX
CROSS-REFERENCE INFORMATION
This function calls:
arraycrop_full Used to crop a rectangular region from an n dimensional array.
checknumericargs Helper utility for checking numeric vector arguments.
This function is called by:
localsum Fast routine for box filtering.
nonmaxsupr Applies nonmaximal suppression on an image of arbitrary dimension.