Description of nlfiltblock_sep
nlfiltblock_sep
PURPOSE
Efficient multidimensional nonlinear but seperable filtering operation.
SYNOPSIS
function I = nlfiltblock_sep(I, dims, fun, varargin)
DESCRIPTION
 Efficient multidimensional nonlinear but seperable filtering operation.
 See nlfilt_sep for a basic discussion of the he concept of a nonlinear
 seperable filters.  This is similar, instead applies operations to
 nonoveralpping blocks (versus a sliding window approach in which all
 overlapping blocks are considered).  Also, as opposed to nlfilt_sep, the
 output returned by this function is smaller then the input I.
 The function fun must be able to take an input of the form
 C=fun(I,radius,param1,...paramk).  The return C must be the result of
 applying the nlfilt operation to the local column (of size 2r+1) of A.
 For example:
   % COMPUTES LOCAL BLOCK SUMS (see localsum_block):
   I = nlfiltblock_sep( I, dims, @rnlfiltblock_sum );
 INPUTS
   I       - matrix to compute fun over
   dims    - size of volume to compute fun over
   fun     - nonlinear filter
   params  - optional parameters for nonlinear filter
 OUTPUTS
   I      - resulting image
 DATESTAMP
   29-Sep-2005  2:00pm
 See also NLFILT_SEP, RNLFILTBLOCK_SUM
CROSS-REFERENCE INFORMATION
This function calls:
arraycrop_full Used to crop a rectangular region from an n dimensional array.
checknumericargs Helper utility for checking numeric vector arguments.
This function is called by:
localsum_block Calculates the sum in non-overlapping blocks of I of size dims.