Description of nlfiltersep
nlfiltersep
PURPOSE
Efficient multidimensional nonlinear but seperable filtering operation.
SYNOPSIS
function I = nlfiltersep(I, dims, shape, fun, varargin)
DESCRIPTION
 Efficient multidimensional nonlinear but seperable filtering operation.
 The concept of a nonlinear seperable filter is not very common, but
 nevertheless can prove useful since computation time can be reduced.
 Consider a funciton like max that is applied to a 2 dim window.  max
 could also be applied to each row of the window, then to the resulting
 column, giving the same result.  This is what is meant here by a
 seperable nonlinear filter.
 If shape is 'block', instead applies operations to nonoveralpping blocks
 (versus a sliding window in which all overlapping blocks are considered).
 The function fun must be able to take an input of the form
 C=fun(I,radius,param1,...paramk).  The return C must have the same size
 as I, and each element of C must be the result of applying the nlfilt
 operation to the local column (of size 2r+1) of A.
 USAGE
  I = nlfiltersep( I, dims, shape, fun, varargin )
 INPUTS
  I       - matrix to compute fun over
  dims    - size of volume to compute fun over, can be scalar
  shape   - 'valid', 'full', 'same' or 'block'
  fun     - nonlinear filter
  params  - optional parameters for nonlinear filter
 OUTPUTS
  I      - resulting image
 EXAMPLE
  load trees; I=ind2gray(X,map);
  Cs = nlfiltersep( I, [11 11], 'same', @nlfiltersep_sum ); % local sums
  Cm = nlfiltersep( I, [11 11], 'same', @nlfiltersep_max ); % local maxes
  figure(1); im(I); figure(2); im(Cs); figure(3); im(Cm);
 See also NLFILTER
 Piotr's Image&Video Toolbox      Version 2.0
 Copyright 2008 Piotr Dollar.  [pdollar-at-caltech.edu]
 Please email me if you find bugs, or have suggestions or questions!
 Licensed under the Lesser GPL [see external/lgpl.txt]
CROSS-REFERENCE INFORMATION
This function calls:
arrayCrop Used to crop a rectangular region from an n dimensional array.
checkNumArgs Helper utility for checking numeric vector arguments.
This function is called by:
localSum Fast routine for box filtering.
nonMaxSupr Applies nonmaximal suppression on an image of arbitrary dimension.