Description of arraycrop_full
arraycrop_full
PURPOSE
Used to crop a rectangular region from an n dimensional array.
SYNOPSIS
function I = arraycrop_full(I, strLocs, endLocs, padEl)
DESCRIPTION
 Used to crop a rectangular region from an n dimensional array.
 Guarantees that the resulting array will have dims as specified by rect
 by filling in locations with padEl if the locations are outside of array.
 USAGE
  I = arraycrop_full( I, strLocs, endLocs, [padEl] )
 INPUTS
  I          - n dimensional array to crop window from
  strLocs    - locs at which to start cropping along each dim
  endLocs    - locs at which to end cropping along each dim
  padEl      - [0] element with which to pad
 OUTPUTS
  I          - cropped array
 EXAMPLE
  I=randn(10);  IC=arraycrop_full( I, [-1 1], [10 10], 0 );
 See also PADARRAY, ARRAYCROP2DIMS
CROSS-REFERENCE INFORMATION
This function calls:
checknumericargs Helper utility for checking numeric vector arguments.
This function is called by:
imshrink Used to shrink a multidimensional array I by integer amount.
nlfilt_sep Efficient multidimensional nonlinear but seperable filtering operation.
nlfiltblock_sep Efficient multidimensional nonlinear but seperable filtering operation.
arraycrop2dims Pads or crops I appropriately so that size(IC)==dims.
mat2cell2 Break matrix up into a cell array of same sized matrices.