Description of c
c
PURPOSE
clc - clear command window.
SYNOPSIS
This is a script file.
DESCRIPTION
 clc - clear command window.
 USAGE
  c
 INPUTS
 OUTPUTS
 EXAMPLE
 See also CLC, CC, CCC
 Piotr's Image&Video Toolbox      Version 1.5
 Copyright 2008 Piotr Dollar.  [pdollar-at-caltech.edu]
 Please email me if you find bugs, or have suggestions or questions!
 Licensed under the Lesser GPL [see external/lgpl.txt]
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
demoGenData Generate data drawn form a mixture of Gaussians.
meanShiftIm Applies the meanShift algorithm to a joint spatial/range image.
meanShiftImExplore Visualization to help choose sigmas for meanShiftIm.
FbReconstruct2d Use to see how much image information is preserved in filter outputs.
filterDog2d Difference of Gaussian (Dog) Filter.
bbApply Functions for manipulating bounding boxes (bb).
bbGt Bounding box (bb) annotations struct, evaluation and sampling routines.
bbLabeler Bounding box or ellipse labeler for static images.
bbNms Bounding box (bb) non-maximal suppression (nms).
behaviorAnnotator Caltech Behavior Annotator.
hogDraw Create visualization of hog descriptor.
imRectRot Create a draggable, resizable, rotatable rectangle or ellipse.
maskEllipse Creates a binary image of an ellipse.
maskGaussians Divides a volume into softly overlapping gaussian windows.
optFlowCorr Calculate optical flow using cross-correlation.
seqPlayer Simple GUI to play seq files.
seqReaderPlugin Plugin for seqIo and videoIO to allow reading of seq files.
seqWriterPlugin Plugin for seqIo and videoIO to allow writing of seq files.