Description of figureresized
figureresized
PURPOSE
Creates a figures that takes up certain area of screen.
SYNOPSIS
function varargout = figuresized(screenratio, varargin)
DESCRIPTION
 Creates a figures that takes up certain area of screen.
 Almost same as figure, except get to specify what fraction of available screen space
 figure should take up.  Figure appears in center of screen.
 INPUTS
   screenratio - controls fraction of screen image takes out (<=.8)
   varargin    - parameters to figure
 OUTPUTS
   varargin    - parameters from figure
 EXAMPLE
   figureresized( .75 )
 DATESTAMP
   29-Sep-2005  2:00pm
 See also FIGURE
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
makemovies [4D] Used to convert R sets of equal length videos into a single movie.
makemoviesets [5D] Used to convert S sets of R videos into a movie.
makemoviesets2 [5D] Used to convert S sets of R videos into a movie.