Description of plot_gaussellipses
plot_gaussellipses
PURPOSE
Plots 2D ellipses derived from 2D Gaussians specified by mus & Cs.
SYNOPSIS
function hs=plot_gaussellipses(mus, Cs, rad)
DESCRIPTION
 Plots 2D ellipses derived from 2D Gaussians specified by mus & Cs.
 USAGE
  hs = plot_gaussellipses( mus, Cs, [rad] )
 INPUTS
  mus     - k x 2 matrix of means
  Cs      - 2 x 2 x k  covariance matricies
  rad     - [2] Number of std to create the ellipse to
 OUTPUTS
  hs      - handles to ellipses
 EXAMPLE
  plot_gaussellipses( [ 10 10; 10 10 ], cat(3,eye(2),eye(2)*2) );
 See also PLOT_ELLIPSE, GAUSS2ELLIPSE
CROSS-REFERENCE INFORMATION
This function calls:
gauss2ellipse Creates an ellipse representing the 2D Gaussian distribution.
plot_ellipse Adds an ellipse to the current plot.
This function is called by:
imageMLG Calculates max likelihood params of Gaussian that gave rise to image G.