Description of tocStatus
tocStatus
PURPOSE
Used to display the progress of a long process.
SYNOPSIS
function tocStatus(id, fracDone)
DESCRIPTION
 Used to display the progress of a long process.
 For more information see ticStatus.
 USAGE
  tocStatus( id, fracDone )
 INPUTS
  id          - unique id of progress indicator
  fracDone    - value in (0,1] indicating percent operation completed
 OUTPUTS
 EXAMPLE
 See also TICSTATUS
 Piotr's Image&Video Toolbox      Version 2.50
 Copyright 2010 Piotr Dollar.  [pdollar-at-caltech.edu]
 Please email me if you find bugs, or have suggestions or questions!
 Licensed under the Lesser GPL [see external/lgpl.txt]
CROSS-REFERENCE INFORMATION
This function calls:
checkNumArgs Helper utility for checking numeric vector arguments.
This function is called by:
meanShiftIm Applies the meanShift algorithm to a joint spatial/range image.
meanShiftPost Some post processing routines for meanShift not currently being used.
bbGt Bounding box (bb) annotations struct, evaluation and sampling routines.
seqIo Utilities for reading and writing seq files.
seqReaderPlugin Plugin for seqIo and videoIO to allow reading of seq files.
dirSynch Synchronize two directory trees (or show differences between them).
diskFill Fill a harddisk with garbage files (useful before discarding disk).
fevalArrays Used to apply the same operation to a stack of array elements.
fevalDistr Run simple jobs locally or in distributed fashion using queue.
fevalImages Used to apply the same operation to all images in given directory.
fevalMats Used to apply the same operation to all .mat files in given directory.