Description of FB_apply_2D
FB_apply_2D
PURPOSE
Applies each of the filters in the filterbank FB to the image I.
SYNOPSIS
function FR = FB_apply_2D(I, FB, shape, show)
DESCRIPTION
 Applies each of the filters in the filterbank FB to the image I.
 To apply to a stack of images:
  IFS = feval_arrays( images, @FB_apply_2D, FB, 'valid' );
 USAGE
  FR = FB_apply_2D( I, FB, [shape], [show] )
 INPUTS
  I       - 2D input array
  FB      - filterbank - MxNxK set of K filters each of size MxN
  shape   - ['full'] option for conv2 'full', 'same', 'valid'
  show    - [0] first figure to use for optional display
 OUTPUTS
  FR      - 3D set of filtered images
 EXAMPLE
  load trees;  X=imresize(X,.5);  load FB_DoG.mat;
  FR = FB_apply_2D( X, FB, 'same', 1 );
 See also CONV2
CROSS-REFERENCE INFORMATION
This function calls:
im IM [2D] Function for displaying grayscale images.
montage2 [3D] Used to display a stack of T images.
This function is called by:
FB_reconstruct_2D Use to see how much image information is preserved in filter outputs.