Description of FB_make_2D
FB_make_2D
PURPOSE
Various 2D filterbanks (hardcoded).
SYNOPSIS
function FB = FB_make_2D(flag, show)
DESCRIPTION
 Various 2D filterbanks (hardcoded).
 USAGE
  FB = FB_make_2D( flag, [show] )
 INPUTS
  flag    - controls type of filterbank to create
            1: filter bank from Serge Belongie
            2: 1st/2nd order DooG filters.  Similar to Gabor filterbank.
            3: similar to Laptev&Lindberg ICPR04
            4: decent seperable steerable? filterbank
            5: berkeley filterbank for textons papers
            6: symmetric DOOG filters
  show    - [0] figure to use for optional display
 OUTPUTS
  FB      - filter bank
 EXAMPLE
  FB = FB_make_2D( 1, 1 );
 See Also
CROSS-REFERENCE INFORMATION
This function calls:
FB_visualize Used to visualize a series of 1D/2D/3D filters.
filter_DOG_2D Difference of Gaussian (Dog) Filter.
filter_DooG_nD n-dim difference of offset Gaussian DooG filter (Gaussian derivative).
filter_gabor_2D Creates an even/odd pair of 2D Gabor filters.
This function is called by: