Description of FB_reconstruct_2D
FB_reconstruct_2D
PURPOSE
Use to see how much image information is preserved in filter outputs.
SYNOPSIS
function I2 = FB_reconstruct_2D(I, FB, patch)
DESCRIPTION
 Use to see how much image information is preserved in filter outputs.
 Reconstructs the orginal image from filter outputs (approximately). The
 filter output for a patch is given by IFR=F*P where F is the set of
 filters in matrix form, P is the patch and IFR is the filter responses at
 the center of the patch.  We want to recover P from IFR and F, this is
 underconstrained but a solution can be found using least squared.  Note
 that each recovered P will be 0 mean if no mean information is captured
 by the filter outputs.  Can apply to a single patch (interatctively
 specified), or the entire image (by keeping the central pixel from each
 patch).
 USAGE
  I2 = FB_reconstruct_2D( I, FB, patch )
 INPUTS
  I      - original image
  FB     - FB to apply and do reconstruction with
  patch  - reconstruct just patch or entire image
 OUTPUTS
  I2     - reconstructed image / patch
 EXAMPLE
  load trees; X=imresize(X,.5); load FB_DoG.mat;
  I2 = FB_reconstruct_2D( X, FB, 0 );
CROSS-REFERENCE INFORMATION
This function calls:
FB_apply_2D Applies each of the filters in the filterbank FB to the image I.
filter_binomial_1D 1D binomial filter (approximation to Gaussian filter)
im IM [2D] Function for displaying grayscale images.
montage2 [3D] Used to display a stack of T images.
arraycrop2dims Pads or crops I appropriately so that size(IC)==dims.
c clc - clear command window.
This function is called by: