Description of FB_visualize
FB_visualize
PURPOSE
Used to visualize a series of 1D/2D/3D filters.
SYNOPSIS
function FB_visualize(FB, show)
DESCRIPTION
 Used to visualize a series of 1D/2D/3D filters.
 For 1D and 2D filterabnks also shows the Fourier spectra of the filters.
 USAGE
  FB_visualize( FB, [show] )
 INPUTS
  FB      - filter bank to visualize (either 2D, 3D, or 4D array)
  show    - [1] figure to use for display
 OUTPUTS
 EXAMPLE
  FB=FB_make_1D(1,0);  FB_visualize( FB, 1 );  %1D
  load FB_DoG.mat;     FB_visualize( FB, 2 );  %2D
  FB=FB_make_3D(1,0);  FB_visualize( FB, 3 );  %3D
CROSS-REFERENCE INFORMATION
This function calls:
filter_visualize_3D Used to visualize a 3D filter.
im IM [2D] Function for displaying grayscale images.
montage2 [3D] Used to display a stack of T images.
This function is called by:
FB_make_1D Various 1D filterbanks (hardcoded).
FB_make_2D Various 2D filterbanks (hardcoded).
FB_make_3D Various 3D filterbanks (hardcoded).