Description of filter_gauss_nD
filter_gauss_nD
PURPOSE
n-dimensional Gaussian filter.
SYNOPSIS
function G = filter_gauss_nD(dims, mu, C, show)
DESCRIPTION
 n-dimensional Gaussian filter.
 Creates an image of a Gaussian with arbitrary covariance matrix. The point [x,y,z]
 refers to the x-th column and y-th row, at the t-th frame.  So for example mu should
 have the format [col,row,t].
 If mu==[], it is calculated to be the center of the image.  C can be a full nxn
 covariance matrix, or an nx1 vector of variance.  In the latter case C is calculated as
 C=diag(C).  If C=[]; then C=(dims/6).^2, ie it is transformed into a vector of variances
 such that along each dimension the variance is equal to (siz/6)^2.
 INPUTS
   dims    - n element vector of dimensions of final Gaussian
   mu      - [optional] n element vector specifying the mean or []
   C       - [optional] nxn covariance matrix, nx1 set of variances, or variance, or []
   show    - [optional] figure to use for display (no display if == 0)
 OUTPUTS
   G   - image of the created Gaussian
 EXAMPLE
   % 2D
   sigma=3; G = filter_gauss_nD( 4*[sigma sigma] + 1, [], [sigma sigma].^2, 1 );
   % 3D
   R = rotation_matrix3D( [1,1,0], pi/4 );
   C = R'*[10^2 0 0; 0 5^2 0; 0 0 16^2]*R;
   G = filter_gauss_nD( [50,50,50], [25,25,25], C, 1 );
 DATESTAMP
   29-Sep-2005  2:00pm
 See also FILTER_GAUSS_1D
CROSS-REFERENCE INFORMATION
This function calls:
filter_visualize_1D Used to help visualize the a 1D filter.
filter_visualize_3D Used to help visualize a 3D filter.
im IM [2D] Function for displaying grayscale images.
montage2 [3D] Used to display a stack of T images.
normpdf2 Normal prob. density function (pdf) with arbitrary covariance matrix.
plot_gaussellipses Plots 2D ellipses derived from 2D Gaussians specified by mus & Cs.
This function is called by:
imageMLG Calculates maximum likelihood parameters of gaussian that gave rise to image G.
mask_gaussians Divides a volume into softly overlapping gaussian windows.