Description of filter_visualize_2D
filter_visualize_2D
PURPOSE
Used to visualize a 2D filter.
SYNOPSIS
function filter_visualize_2D(F, scanline, show)
DESCRIPTION
 Used to visualize a 2D filter.
 Marks local image maxima with a green '+' and minima with a red '+'. Also
 shows the fft response of the filter.  Can optionally also plot a
 scanline through either center row/column.
 USAGE
  filter_visualize_2D( F, scanline, [show] )
 INPUTS
  F         - filter to visualize
  scanline  - [0] 'row' OR 'col': display centeral row OR col line
  show      - [1] figure to use for display (0->uses current)
 OUTPUTS
 EXAMPLE
  F = filter_DOG_2D( 15, 10, 1 );
  filter_visualize_2D( F, 'row', 1 );
 See also FILTER_VISUALIZE_1D, FILTER_VISUALIZE_3D
CROSS-REFERENCE INFORMATION
This function calls:
im IM [2D] Function for displaying grayscale images.
This function is called by:
filter_DOG_2D Difference of Gaussian (Dog) Filter.
filter_DooG_nD n-dim difference of offset Gaussian DooG filter (Gaussian derivative).
filter_gabor_2D Creates an even/odd pair of 2D Gabor filters.
filter_gauss_nD n-dimensional Gaussian filter.