Description of filter_visualize_1D
filter_visualize_1D
PURPOSE
Used to visualize a 1D filter.
SYNOPSIS
function filter_visualize_1D(f, show)
DESCRIPTION
 Used to visualize a 1D filter.
 Marks local filter maxima with a green '+' and minima with a red '+'.
 Also shows the fft response of the filter.
 USAGE
  filter_visualize_1D( f, [show] )
 INPUTS
  f       - filter to visualize
  show    - [1] figure to use for display (0->uses current)
 OUTPUTS
 EXAMPLE
  f = filter_binomial_1D( 10, 0 );
  filter_visualize_1D( f, 1 )
 See also FILTER_VISUALIZE_2D
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
filter_DooG_nD n-dim difference of offset Gaussian DooG filter (Gaussian derivative).
filter_binomial_1D 1D binomial filter (approximation to Gaussian filter)
filter_gabor_1D Creates an even/odd pair of 1D Gabor filters.
filter_gauss_1D 1D Gaussian filter.
filter_gauss_nD n-dimensional Gaussian filter.