Description of filter_DooG_nD
filter_DooG_nD
PURPOSE
n-dim difference of offset Gaussian DooG filter (Gaussian derivative).
SYNOPSIS
function dG = filter_DooG_nD(dims, sigmas, nderivs, show)
DESCRIPTION
 n-dim difference of offset Gaussian DooG filter (Gaussian derivative).
 Creates a nd derivative of Gaussian kernel.  For all but d==1 use
 primarily for visualization purposes -- for filtering better to use the
 indvidiual seperable kernels for efficiency purposes.
 USAGE
  dG = filter_DooG_nD( dims, sigmas, nderivs, [show] )
 INPUTS
  dims    - nd element vector of dimensions of final Gaussian
  sigmas  - sigmas for nd Gaussian
  nderivs - order of derivative along each of the nd dimensions
  show    - [0] figure to use for optional display
 OUTPUTS
  dG      - The derivative of Gaussian filter
 EXAMPLE
  dG1 = filter_DooG_nD( 43, 2, 3, 1 ); %1D
  dG2 = filter_DooG_nD( [41 41], [3 3], [1,1], 2 ); %2D
  dG3 = filter_DooG_nD( [101 101 101], [4,4,10], [1,1,0], 3 ); %3D
 See also FILTER_GAUSS_ND, NORMPDF2, FILTER_DOG_2D, FILTER_GABOR_2D
CROSS-REFERENCE INFORMATION
This function calls:
filter_gauss_nD n-dimensional Gaussian filter.
filter_visualize_1D Used to visualize a 1D filter.
filter_visualize_2D Used to visualize a 2D filter.
filter_visualize_3D Used to visualize a 3D filter.
This function is called by:
FB_make_2D Various 2D filterbanks (hardcoded).
FB_make_3D Various 3D filterbanks (hardcoded).