Description of filter_DOG_2D
filter_DOG_2D
PURPOSE
Difference of Gaussian (Dog) Filter.
SYNOPSIS
function G = filter_DOG_2D(r, sig, order, show)
DESCRIPTION
 Difference of Gaussian (Dog) Filter.
 Adapted from code by Serge Belongie.  Takes a "difference of Gaussian" - all centered
 on the same point but with different values for sigma.
 INPUTS
   r       - Final filter will be 2*r+1 on each side
   sig     - standard deviation of central Gaussian
   order   - should be either 1 or 2
   show    - [optional] figure to use for display (no display if == 0)
 OUTPUTS
   G       - final filter
 EXAMPLE
   G = filter_DOG_2D( 6, 3, 1, 1 );
 DATESTAMP
   29-Sep-2005  2:00pm
 See also FILTER_DOOG_2D
CROSS-REFERENCE INFORMATION
This function calls:
filter_visualize_2D Used to help visualize a 2D filter.
c clc
normpdf2 Normal prob. density function (pdf) with arbitrary covariance matrix.
This function is called by:
FB_make_2D Various ways to make filterbanks. See inside of this file for details.