Description of filter_DOOG_3D
filter_DOOG_3D
PURPOSE
3D difference of offset Gaussian (DooG) filters.
SYNOPSIS
function dG = filter_DOOG_3D(r, sigmas, nderivs, show)
DESCRIPTION
 3D difference of offset Gaussian (DooG) filters.
 Creates a 3D derivative of Gaussian kernel.  Use primarily for visualization purposes.
 For filtering better to use the indvidiual seperable kernels for efficiency purposes.
 INPUTS
   r       - final mask will be NxNxN where N=2r+1
   sigmas  - sigmas for 3D Gaussian
   nderivs - order of derivative along each dimension
   show    - [optional] whether or not to visually display the kernel
 OUTPUTS
   dG      - The derivative of Gaussian mask
 EXAMPLE
   dG = filter_DOOG_3D( 50, [4,4,10], [1,1,0], 1 );
 DATESTAMP
   29-Sep-2005  2:00pm
 See also FILTER_DOOG_1D, FILTER_DOOG_2D
CROSS-REFERENCE INFORMATION
This function calls:
filter_visualize_3D Used to help visualize a 3D filter.
montage2 [3D] Used to display a stack of T images.
This function is called by:
FB_make_3D Various ways to make filterbanks. See inside of this file for details.