Description of filter_visualize_3D
filter_visualize_3D
PURPOSE
Used to visualize a 3D filter.
SYNOPSIS
function filter_visualize_3D(F, frac, show)
DESCRIPTION
 Used to visualize a 3D filter.
 Dark lobes correspond to negative areas.  Surfaces shown are drawn at a
 percentage of the peak filter response detemined by frac.
 USAGE
  filter_visualize_3D( F, frac, [show] )
 INPUTS
  F       - 3D filter to visualize
  frac    - frac of max value of F at which to draw surfaces.
  show    - [1] figure to use for display (0->uses current)
 OUTPUTS
 EXAMPLE
  F = filter_DooG_nD( [51 51 101], [3 3 5], [1 2 3], 0 );
  filter_visualize_3D( F, .1, 1 );
 See also FILTER_VISUALIZE_2D
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
FB_visualize Used to visualize a series of 1D/2D/3D filters.
filter_DooG_nD n-dim difference of offset Gaussian DooG filter (Gaussian derivative).
filter_gauss_nD n-dimensional Gaussian filter.