Description of filterVisualize
filterVisualize
PURPOSE
Used to visualize a 1D/2D/3D filter.
SYNOPSIS
function filterVisualize(f, show, arg)
DESCRIPTION
 Used to visualize a 1D/2D/3D filter.
 For 1d filters:
  Marks local filter maxima with a green '+' and minima with a red '+'.
  Also shows the fft response of the filter.
 For 2d filters:
  Marks local filter maxima with a green '+' and minima with a red '+'.
  Also shows the fft response of the filter.  Can optionally also plot a
  scanline through either center row/column.
 For 3d filters:
  Dark lobes correspond to negative areas.  Surfaces shown are drawn at a
  percentage of the peak filter response detemined by frac.
 USAGE
  filterVisualize( f, [show], [arg] )
 INPUTS
  f         - filter to visualize
  show      - [1] figure to use for display (0->uses current)
  arg       - different meanding depending on dimension
              d=1: [] not used
              d=2: [''] 'row' OR 'col': display centeral row OR col line
              d=3: [.1] frac of max value of f at which to draw surfaces
 OUTPUTS
 EXAMPLE
  f=filterBinomial1d( 10, 0 ); filterVisualize( f, 1 ); %1d
  f=filterDog2d( 15, 10, 1 ); filterVisualize( f, 2, 'row' ); %2d
  f=filterDoog([51 51 99],[3 3 5],[1 2 3],0); filterVisualize(f,4,.1); %3d
 See also FILTERGAUSS, FBVISUALIZE
 Piotr's Image&Video Toolbox      Version 2.0
 Copyright 2008 Piotr Dollar.  [pdollar-at-caltech.edu]
 Please email me if you find bugs, or have suggestions or questions!
 Licensed under the Lesser GPL [see external/lgpl.txt]
CROSS-REFERENCE INFORMATION
This function calls:
im Function for displaying grayscale images.
This function is called by:
FbVisualize Used to visualize a series of 1D/2D/3D filters.
filterBinomial1d 1D binomial filter (approximation to Gaussian filter)
filterDog2d Difference of Gaussian (Dog) Filter.
filterDoog n-dim difference of offset Gaussian DooG filter (Gaussian derivative).
filterGabor1d Creates an even/odd pair of 1D Gabor filters.
filterGabor2d Creates an even/odd pair of 2D Gabor filters.
filterGauss n-dimensional Gaussian filter.