Description of clfLda
clfLda
PURPOSE
Create a Linear Discriminant Analysis (LDA) classifier.
SYNOPSIS
function clf = clfLda(p, type, prior)
DESCRIPTION
 Create a Linear Discriminant Analysis (LDA) classifier.
 Same algorithm as matlab's function 'classify' (in the statistics
 toolbox).  Nice to have in form that actually stores a model that can be
 applied multiple times. For the meaning and usage of prior and type see
 classify.m
 USAGE
  clf = clfLda( p, [type], [prior] )
 INPUTS
  p       - data dimension
  type    - ['linear'] 'linear', 'quadratic', 'mahalanobis'
  prior   - [] prior to use
 OUTPUTS
  clf     - an LDA model ready to be trained (see clfLdaTrain)
 EXAMPLE
 See also NFOLDXVAL, CLASSIFY, CLFLDATRAIN, CLFLDAFWD
 Piotr's Image&Video Toolbox      Version 2.0
 Copyright 2008 Piotr Dollar.  [pdollar-at-caltech.edu]
 Please email me if you find bugs, or have suggestions or questions!
 Licensed under the Lesser GPL [see external/lgpl.txt]
CROSS-REFERENCE INFORMATION
This function calls:
clfLdaFwd Apply the Linear Discriminant Analysis (LDA) classifier to data X.
clfLdaTrain Train a Linear Discriminant Analysis (LDA) classifier.
This function is called by:
demoClassify DEMOCLASSIFY A demo used to test and demonstrate the usage of classifiers (clf*)