Description of confMatrixShow
confMatrixShow
PURPOSE
Used to display a confusion matrix.
SYNOPSIS
function confMatrixShow(CM, types, pvPairs, nDigits)
DESCRIPTION
 Used to display a confusion matrix.
 See confMatrix for general format and info on confusion matricies.  This
 function normalizes the CM before displaying, hence all values range in
 [0,1] and rows sum to 1.
 USAGE
  confMatrixShow( CM, [types], [pvPairs], [nDigits] )
 INPUTS
  CM          - [nTypes x nTypes] confusion array -- see confMatrix
  types       - [] cell array of length nTypes of text labels
  pvPairs     - [] parameter / value list for text.m
  nDigits     - [2] number of digits after decimal to display
 OUTPUTS
 EXAMPLE
  cliptypes = { 'anger','disgust','fear','joy','sadness','surprise' };
  confMatrixShow( rand(6)/3+eye(6), cliptypes, {'FontSize',20} )
  title('confusion matrix','FontSize',24);
 See also CONFMATRIX, TEXT2
 Piotr's Image&Video Toolbox      Version 2.0
 Copyright 2008 Piotr Dollar.  [pdollar-at-caltech.edu]
 Please email me if you find bugs, or have suggestions or questions!
 Licensed under the Lesser GPL [see external/lgpl.txt]
CROSS-REFERENCE INFORMATION
This function calls:
imLabel Improved method for labeling figure axes.
int2str2 Convert integer to string of given length; improved version of int2str.
This function is called by:
nfoldxval Runs n-fold cross validation on data with a given classifier.