Description of democluster
democluster
PURPOSE
Clustering demo.
SYNOPSIS
This is a script file.
DESCRIPTION
 Clustering demo.
 Used to test different clustering algorithms on 2D and 3D mixture of
 gaussian data. Alter demo by edititing this file.
 USAGE
  democluster
 INPUTS
 OUTPUTS
 EXAMPLE
  democluster
CROSS-REFERENCE INFORMATION
This function calls:
demogendata Generate data drawn form a mixture of Gaussians.
dist_euclidean Calculates the SQUARED Euclidean distance between vectors [FAST].
distmatrix_show Useful visualization of a distance matrix of clustered points.
kmeans2 Fast version of kmeans clustering.
meanshift meanshift clustering algorithm.
visualize_data Project high dim. data unto principal components (PCA) for visualization.
im IM [2D] Function for displaying grayscale images.
This function is called by: