Description of demogendata
demogendata
PURPOSE
Generate data drawn form a mixture of Gaussians.
SYNOPSIS
function [X,IDX,T,IDT] = demogendata(n,m,k,d,c,e,f)
DESCRIPTION
 Generate data drawn form a mixture of Gaussians.
 Adapted from code by [Nikos Vlassis, 2000].
 For definitions see [Dasgupta, 1999].
 INPUTS
   n - size of training set
   m - size of test set
   k - number of components
   d - dimension
   c - separation degree
   e - maximum eccentricity
   f - [optional] fraction of points that are noise (uniformly distributed)
 OUTPUTS
   X    - training set (n x d)
   IDX  - cluster membership [see kmeans2.m]
   T    - test set (m x d)
   IDT  - cluster membership [see kmeans2.m]
 DATESTAMP
   29-Sep-2005  2:00pm
 See also VISUALIZE_DATA, DEMOCLUSTER, DEMOCLASSIFY
CROSS-REFERENCE INFORMATION
This function calls:
c clc
This function is called by:
democlassify A demo used to test and demonstrate the usage of classifiers (clf_*)
democluster Clustering demo.