Description of demoClassify
demoClassify
PURPOSE
DEMOCLASSIFY A demo used to test and demonstrate the usage of classifiers (clf*)
SYNOPSIS
function demoClassify
DESCRIPTION
DEMOCLASSIFY A demo used to test and demonstrate the usage of classifiers (clf*)
 To change the demo parameters alter this function. Note that the
 visualization of the train and test data may look different due to
 different 2D projections (see visualizeData).
 USAGE
  demoClassify
 INPUTS
 OUTPUTS
 EXAMPLE
  demoClassify
 See also CLFKNN, CLFLDA, CLFSVM, CLFECOC, CLFDECTREE, VISUALIZEDATA
 Piotr's Image&Video Toolbox      Version 2.0
 Copyright 2008 Piotr Dollar.  [pdollar-at-caltech.edu]
 Please email me if you find bugs, or have suggestions or questions!
 Licensed under the Lesser GPL [see external/lgpl.txt]
CROSS-REFERENCE INFORMATION
This function calls:
clfEcoc Wrapper for ecoc that makes ecoc compatible with nfoldxval.
clfKnn Create a k nearest neighbor classifier.
clfLda Create a Linear Discriminant Analysis (LDA) classifier.
clfSvm Wrapper for svm that makes svm compatible with nfoldxval.
confMatrix Generates a confusion matrix according to true and predicted data labels.
demoGenData Generate data drawn form a mixture of Gaussians.
visualizeData Project high dim. data unto principal components (PCA) for visualization.
montage2 Used to display collections of images and videos.
This function is called by: