Description of distmatrix_show
distmatrix_show
PURPOSE
Useful visualization of a distance matrix of clustered points.
SYNOPSIS
function [D, Dsm] = distmatrix_show(D, IDX, show)
DESCRIPTION
 Useful visualization of a distance matrix of clustered points.
 D is sorted into k blocks, where the ith block contains all the points in
 cluster i. When D is displayed the blocks are shown explicitly.  Hence
 for a good clustering (under a spherical gaussian assumption) the
 'diagnol' blocks ought to be mostly dark, and all other block ought to be
 relatively white.  One can thus quickly visualize the quality of the
 clustering, or even how clusterable the points are.  Outliers (according
 to IDX) are removed from D.
 USAGE
  [D, Dsm] = distmatrix_show( D, IDX, [show] )
 INPUTS
  D       - nxn distance matrix
  IDX     - cluster membership [see kmeans2.m]
  show    - [1] will display results in figure(show)
 OUTPUTS
  D       - sorted nxn distance matrix
  Dsm     - sorted and smoothed nxn distance matrix
 EXAMPLE
  % not the best example since points are already ordered
  [X,IDXtrue] = demogendata(100,0,2,2,10,2,0);
  distmatrix_show( dist_euclidean(X,X), IDXtrue );
 See also VISUALIZE_DATA, KMEANS2
CROSS-REFERENCE INFORMATION
This function calls:
IDX2order Converts class labels into an ordering.
im IM [2D] Function for displaying grayscale images.
This function is called by:
democluster Clustering demo.