Description of dist_euclidean
dist_euclidean
PURPOSE
Calculates the SQUARED Euclidean distance between vectors [FAST].
SYNOPSIS
function D = dist_euclidean(X, Y)
DESCRIPTION
 Calculates the SQUARED Euclidean distance between vectors [FAST].
 Let X be an m-by-p matrix representing m points in p-dimensional space
 and Y be an n-by-p matrix representing another set of points in the same
 space. This function computes the m-by-n distance matrix D where D(i,j)
 is the SQUARED Euclidean distance between X(i,:) and Y(j,:). Running time
 is O(m*n*p).
 If x is a single data point, here is a faster, inline version to use:
  D = sum( (Y - ones(size(Y,1),1)*x).^2, 2 )';
 USAGE
  D = dist_euclidean( X, Y )
 INPUTS
  X   - [m x p] matrix of m p-dimensional vectors
  Y   - [n x p] matrix of n p-dimensional vectors
 OUTPUTS
  D   - [m x n] distance matrix
 EXAMPLE
  X = [randn(100,5)]; Y=randn(40,5)+2;
  D = dist_euclidean( [X; Y], [X; Y] ); im(D)
 See also DIST_CHISQUARED, DIST_EMD, DIST_L1, DIST_COSINE
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
clf_knn Create a k nearest neighbor classifier.
democluster Clustering demo.
kmeans2 Fast version of kmeans clustering.
meanshiftim_explore Visualization to help choose sigmas for meanshiftim.
meanshift_post Some post processing routines for meanshift not currently being used.
rbfComputeBasis Get locations and sizes of radial basis functions for use in rbf network.