Description of fernsInds
fernsInds
PURPOSE
Compute indices for each input by each fern.
SYNOPSIS
function inds = fernsInds(data, fids, thrs)
DESCRIPTION
 Compute indices for each input by each fern.
 USAGE
  inds = fernsInds( data, fids, thrs )
 INPUTS
  data     - [NxF] N length F binary feature vectors
  fids     - [MxS] feature ids for each fern for each depth
  thrs     - [MxS] threshold corresponding to each fid
 OUTPUTS
  inds     - [NxM] computed indices for each input by each fern
 EXAMPLE
 See also fernsClfTrain, fernsClfApply
 Piotr's Image&Video Toolbox      Version 2.50
 Copyright 2010 Piotr Dollar.  [pdollar-at-caltech.edu]
 Please email me if you find bugs, or have suggestions or questions!
 Licensed under the Lesser GPL [see external/lgpl.txt]
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
fernsClfApply Apply learned fern classifier.
fernsClfTrain Train random fern classifier.
fernsRegApply Apply learned fern regressor.
fernsRegTrain Train boosted fern regressor.