Description of meanshiftim_explore
meanshiftim_explore
PURPOSE
Visualization to help choose sigmas for meanshiftim.
SYNOPSIS
function meanshiftim_explore(I, X, sig_spt, sig_rng, show)
DESCRIPTION
 Visualization to help choose sigmas for meanshiftim.
 Displays the original image I, and prompts user to select a point on the image.  For
 given point, calculates the distance (both spatial and range) to every other point in
 the image.   It shows the results in a number of panes, which include 1) the original
 image I, 2) Srange - similarity based on range only, 3) Seuc - similarity based on
 Euclidean distance only, and 4) overall similarity.  Finally, in each image the green
 dot (possibly occluded) shows the original point, and the blue dot shows the new mean of
 the window after 1 step of meanshift.
 INPUTS
   I       - MxN image for display
   X       - MxNxP data array, P may be 1 (X may be same as I)
   sig_spt - integer specifying spatial standard deviation
   sig_rng - value specifying the standard deviation of the range data
   show    - [optional] will display results in figure(show)
 EXAMPLE
   I=double(imread('cameraman.tif'))/255;
   meanshiftim_explore( I, I, 5, .2, 1 );
 DATESTAMP
   25-Oct-2005  4:00pm
 See also MEANSHIFTIM
CROSS-REFERENCE INFORMATION
This function calls:
dist_euclidean Calculates the Euclidean distance between vectors [FAST].
im IM [2D] Function for displaying grayscale images.
c clc
This function is called by: