Description of acfDemoInria
acfDemoInria
PURPOSE
Demo for aggregate channel features object detector on Inria dataset.
SYNOPSIS
This is a script file.
DESCRIPTION
 Demo for aggregate channel features object detector on Inria dataset.
 (1) Download data and helper routines from Caltech Peds Website
  www.vision.caltech.edu/Image_Datasets/CaltechPedestrians/
  (1a) Download INRIA files: set00.tar, set01.tar, and annotations.zip
  (1b) Copy above three files to dataDir/ and untar/unzip contents
  (1c) Download evaluation code (routines necessary for extracting images)
 (2) Set dataDir/ variable below to point to location of INRIA data.
 (3) Launch "matlabpool open" for faster training if available.
 (4) Run demo script and enjoy your newly minted fast ped detector!
 Note: pre-trained model files are provided (delete to re-train).
 Re-training may give slightly variable results on different machines.
 Piotr's Image&Video Toolbox      Version 3.22
 Copyright 2013 Piotr Dollar & Ron Appel.  [pdollar-at-caltech.edu]
 Please email me if you find bugs, or have suggestions or questions!
 Licensed under the Simplified BSD License [see external/bsd.txt]
CROSS-REFERENCE INFORMATION
This function calls:
imResample Fast bilinear image downsampling/upsampling.
acfDetect Run aggregate channel features object detector on given image(s).
acfModify Modify aggregate channel features object detector.
acfTest Test aggregate channel features object detector given ground truth.
acfTrain Train aggregate channel features object detector.
bbApply Functions for manipulating bounding boxes (bb).
bbGt Bounding box (bb) annotations struct, evaluation and sampling routines.
im Function for displaying grayscale images.
seqIo Utilities for reading and writing seq files.
This function is called by: