Description of acfTest
acfTest
PURPOSE
Test aggregate channel features object detector given ground truth.
SYNOPSIS
function [miss,roc,gt,dt] = acfTest(varargin)
DESCRIPTION
 Test aggregate channel features object detector given ground truth.
 USAGE
  [miss,roc,gt,dt] = acfTest( pTest )
 INPUTS
  pTest    - parameters (struct or name/value pairs)
   .name     - ['REQ'] detector name
   .imgDir   - ['REQ'] dir containing test images
   .gtDir    - ['REQ'] dir containing test ground truth
   .pLoad    - [] params for bbGt>bbLoad for test data (see bbGt>bbLoad)
   .thr      - [.5] threshold on overlap area for comparing two bbs
   .mul      - [0] if true allow multiple matches to each gt
   .reapply  - [0] if true re-apply detector even if bbs already computed
   .ref      - [10.^(-2:.25:0)] reference points (see bbGt>compRoc)
   .lims     - [3.1e-3 1e1 .05 1] plot axis limits
   .show     - [0] optional figure number for display
 OUTPUTS
  miss     - log-average miss rate computed at reference points
  roc      - [nx3] n data points along roc of form [score fp tp]
  gt       - [mx5] ground truth results [x y w h match] (see bbGt>evalRes)
  dt       - [nx6] detect results [x y w h score match] (see bbGt>evalRes)
 EXAMPLE
 See also acfTrain, acfDetect, acfDemoInria, bbGt
 Piotr's Image&Video Toolbox      Version 3.22
 Copyright 2013 Piotr Dollar & Ron Appel.  [pdollar-at-caltech.edu]
 Please email me if you find bugs, or have suggestions or questions!
 Licensed under the Simplified BSD License [see external/bsd.txt]
CROSS-REFERENCE INFORMATION
This function calls:
acfDetect Run aggregate channel features object detector on given image(s).
bbGt Bounding box (bb) annotations struct, evaluation and sampling routines.
getPrmDflt Helper to set default values (if not already set) of parameter struct.
plotRoc Function for display of rocs (receiver operator characteristic curves).
This function is called by:
acfDemoCal Demo for aggregate channel features object detector on Caltech dataset.
acfDemoInria Demo for aggregate channel features object detector on Inria dataset.